.TH sedcli-kmip 8
.SH NAME
sedcli-kmip \- autoprovision and autounlock TCG Opal SEDs using Key Management
Server (KMS)

.SH SYNOPSIS

\fBsedcli-kmip\fR <command> [options...]

.SH DESCRIPTION
Sedcli-kmip is part of sedcli package and allows system Administrator/Operator
to automatically provision and automatically unlock NVMe SEDs that are TCG Opal
compliant.

.PP
Automatic management requires sedcli-kmip to be configured with OASIS KMIP (Key
Management Interoperability Protocol) compatible Key Management Server. There
are commercial and open source implementations of KMIP server available.
Sedcli-kmip has been developed and tested using PyKMIP implementation.

.PP
Sedcli-kmip when run for the first time on a given platform, communicates with
KMS and generates Platform Encryption Key (PEK) on it. PEK is a single per
platform AES-256 bits long key that is used to wrap/unwrap individual disk keys
called Disk Encryption Key (DEK). Encrypted version of DEK is stored in sedcli
metadata region in Opal datastore on disk itself.

.PP
NVMe SED provisioning may be triggered manually in command line or automatically
on hot-insert event or OS boot. This requires proper udev rules to be installed.
When NVMe SED is provisioned for security DEK key is used for SID and Admin1
authorities.

.PP
Sedcli-kmip performs secure communication with KMS using SSL. KMS uses
certificate based authentication and authorization. Path to sedcli-kmip client
certificate and CA certificate should be stored in /etc/sedcli/sedcli.conf
file.

.PP
It is possible to perform periodic key rotation using key backup functionality.
User needs to store old DEK key in a backup file and then reprovision SSD using
backup file to authenticate to the drive and perform necessary updates.

.SH OPTIONS

.IP "\fB\-\-help\fR"
Prints global and command specific help on available commands and usage

.IP "To print command specific help use following syntax:"
.IP "\fBsedcli-kmip <command> --help\fR"
.IP "For example:"
.IP "\fBsedcli-kmip --provision --help\fR"

.SH COPYRIGHT
Copyright (C) 2018-2019, 20222-2023 Solidigm. All Rights Reserved.

.SH AUTHOR
This manual page was created by Piotr Rudnicki <piotr.rudnicki@solidigm.com>

.SH FILES
.PP
sedcli-kmip
.PP
/etc/sedcli/sedcli.conf

.SH SEE ALSO
.TP
sedcli(8)
